version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
      nodejs: 16
   
    commands:
        # install npm
      - pip install pylint
      - pip install pylint-exit
      - pip install bandit
      - pylint serverfunctions --max-line-length=400 || pylint-exit $?
      - bandit -r serverfunctions -ll --exit-zero
       
  build:
    commands:
      # run build script
      - echo "Zipping deployment package..."
      - zip -r9 deployment_package.zip serverfunctions
     
artifacts:
  # include all files required to run application
  # notably excluded is node_modules, as this will cause overwrite error on deploy
  files:
    - public/**/*
    - src/**/*
    - package.json