version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  
    commands:
      - npm install
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - '**/*'
cache:
  paths:
    - node_modules